Feature/query wizard
tenders-exposed/elvis-ember pull request #489
Opened 2019-03-27 01:55 UTC by ca1yps0

2019-03-27 08:24 UTC, nightsh commented
- steps line is not aligned properly (1-2 px to the right should do)
- "loading" bits are not set on wizard step change (hence a slower "loading" feedback)
- step titles look like anchors, they shouldn't
- settings: images don't have correct paths
- settings drop downs styling

2019-03-29 09:19 UTC, victor-nitu requested changes
- [x] you should receive an error message if you didn't select anything
  - [x] if nothing was selected in step 1, allow step 2 but don't allow step 3 if nothign was selected
- [x] if you select a company, then you go back and change countries, when you go back to actors the old selection is still there (make it disappear if you change any previous steps)
- [x] steps line is not aligned properly (1-2 px to the right should do)
- [x] "loading" bits are not set on wizard step change (hence a slower "loading" feedback)
- [x] step titles look like anchors, they shouldn't
- [x] settings: images don't have correct paths
- [x] settings drop downs styling

2019-04-04 17:52 UTC, victor-nitu approved these changes

2019-04-24 06:41 UTC, victor-nitu requested changes
Not going to go through all the diff, please remove all dead code before anything.

2019-04-24 06:41 UTC, nightsh commented on app/components/actor-select-guru.js
> +  /*selectAllOptions: observer('checkboxIsSelected', function() {
dead code

2019-04-24 06:41 UTC, nightsh commented on app/components/actor-select-guru.js
> +  // checkActors: false,
dead code

2019-04-24 06:41 UTC, nightsh commented on app/components/actor-select-guru.js
> +      // this.attrs.onSelect(this.get('_value'));
more dead code

2019-04-24 21:27 UTC, zufanka commented
Great job guys. @ca1yps0 @nightsh @chutko 
There are still a couple of things to fix:

**BUGS**
- [ ] if you don't select a CPV, the "Settings" step is empty
- [ ] if you go to "Create a network" from the network view (back to the query builder), the previous countries are actually still selected, but you don't see it in the first step (if you go a step further, the flags appear). Everything should be deselected if you do this
- [ ] when I press "Launch the network", a loader should appear
- [ ] flags missing here
![image](https://user-images.githubusercontent.com/2411066/56694788-ca5bc080-66e7-11e9-87a2-a06c09647cba.png)
- [ ] This errormessage appears when server returns 500. This should NOT be the case as it's NOT the problem. Can we change it to "This should not be happening. Please send us an email at tech@tenders.exposed if it is." or something like that?
![image](https://user-images.githubusercontent.com/2411066/56694959-3ccca080-66e8-11e9-9f4d-979af5a47ff5.png)


**STYLING**
- [ ] this selection goes into the footer. Can we make it higher?
![image](https://user-images.githubusercontent.com/2411066/56692515-a649b080-66e2-11e9-8f01-45865be27adc.png)
- [ ] there should be more space between these
![image](https://user-images.githubusercontent.com/2411066/56694220-7f8d7900-66e6-11e9-8eaf-fedc710a7806.png)
- [ ] there should be definitely more space here
![image](https://user-images.githubusercontent.com/2411066/56694285-a21f9200-66e6-11e9-8341-a3ce66a1fb46.png)
- [ ] the "Node types" and "edge types" as well as the "name of the network" are a bit small and difficult to read. @chutko can we make them pop out more?
![image](https://user-images.githubusercontent.com/2411066/56694365-c5e2d800-66e6-11e9-8520-a026dcbf65b2.png)
- [ ] can we have these on a transparent background? @chutko 
![image](https://user-images.githubusercontent.com/2411066/56694398-d5fab780-66e6-11e9-87cc-20cca19522ca.png)
- [ ] There should be some indicator that the user chose actors here (no countries chosen now)
![image](https://user-images.githubusercontent.com/2411066/56694859-0000a980-66e8-11e9-9d3a-d04b9165bb2b.png)

2019-05-02 15:58 UTC, nightsh commented
@zufanka I will merge and copy your message into a new issue - we will surely rebranch after merging but this is getting again and again out of sync with develop and it's becoming a hassle to maintain it open & mergeable for so long.

2019-05-02 15:59 UTC, merged